apiVersion: v1
kind: Secret
metadata:
  name: repo-devops-project
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: {GITHUB_REPO_URL}
  username: {GITHUB_USERNAME}
  password: {GITHUB_PAT_TOKEN}
