apiVersion: v1
kind: Secret
metadata:
  name: secret-repo-deploy
  namespace: default
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": "<GIT_USERNAME>",
          "password": "<GIT_PAT_TOKEN>"
        }
      }
   }
