receivers:
  - name: slack-notifications
    slack_configs:
      - api_url: 'YOUR_SLACK_WEBHOOK'
        channel: 'YOUR_CHANNEL_NAME'
        # example: 
        # channel: "#my-channel"
        send_resolved: true
        title: >-
          🚨 {{ .Status | toUpper }} - {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}
        text: >-
          {{ range .Alerts }}

          *🚨 Alert Name:* {{ .Labels.alertname }}

          *⚠️ Severity:* {{ .Labels.severity }}

          *📦 Job:* {{ .Labels.job }}

          *🖥️ Instance:* {{ .Labels.instance }}
          
          *📝 Description:* 
          {{ .Annotations.description }}
          
          *⏰ Status:* {{ $.Status }}
          ---
          {{ end }}
