{
 "title": "FastAPI App Metrics Dashboard.",
 "description": "FastAPI App Metrics Dashborad.",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Application-Status.",
   "type": "stat",
   "description": "Application-Status.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"janemils-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate.",
   "type": "timeseries",
   "description": "Requests per second over the last 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage (MB).",
   "type": "timeseries",
   "description": "CPU Usage (MB).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"janemils-app\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (MB)",
   "type": "gauge",
   "description": "Unit: mebibytes (MiB)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"janemils-app\"} / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests by Endpoint",
   "type": "barchart",
   "description": "Requests by Endpoint",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (endpoint)(\r\n  increase(http_requests_total{job=\"janemils-app\"}[5m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests by Status Code.",
   "type": "piechart",
   "description": "Requests by Status Code.\n200 -> Success\n404 -> Not Found\n500 -> Internal Server Error",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status)(\r\n  increase(http_requests_total{job=\"janemils-app\"}[5m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx Error Rate",
   "type": "timeseries",
   "description": "5xx Error Rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"5..\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}