name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      IMAGE_NAME: ghcr.io/janemils/devops-project-1

    steps:
    # Checkout code.
    - name: Checkout
      uses: actions/checkout@v4

    # Login to GHCR.
    - name: Login to GHCR
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    # Build Docker image.
    - name: Build image
      run: |
        docker build \
          -t $IMAGE_NAME:${{ github.sha }} \
          -f Day-02/Dockerfile \
          .

    # Push image.
    - name: Push image
      run: |
        docker push $IMAGE_NAME:${{ github.sha }}

    # Updating the image in the manifest.    
    - name: Update image in manifest
      run: |
        sed -i "s|image: ghcr.io/janemils/devops-project-1:.*|image: $IMAGE_NAME:${{ github.sha }}|" Day-04/deployment.yaml

